name: spamascotas
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  sqflite: ^2.0.1
  path: ^1.8.0
  url_launcher: ^6.2.4
  flutter_phone_direct_caller: ^2.1.1
  path_provider: ^2.1.2
  file_picker: ^6.1.1
  excel: ^2.0.7
  csv: ^5.1.1
  table_calendar: ^3.0.9
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  fluttertoast: ^8.2.4
  fl_chart: ^0.35.0
  flutter_charts: ^0.5.2
  shared_preferences: ^2.2.2
  mailer: ^6.1.0
  flutter_email_sender: ^6.0.2
  flutter_foreground_task: ^6.1.3
  flutter_share: ^2.0.0
  pdf: ^3.10.8
  share_plus: ^7.2.2
  whatsapp_unilink: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.0.8
  share: ^2.0.4




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/avatar.png"


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/avatar.png
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800

